"""
This is some code for generating GIF from combining images generated by script. 
The Delay is not work properly, so standard work fine or code can be improved 
"""
import os
from PIL import Image
import random
import string

def combine_images(folder_path, delay=500):
    # Getting list of images in folder 
    images = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith('.png')]
    images.sort()

    # Generating a unique filename for a product
    chars = string.ascii_letters + string.digits
    random_string = ''.join(random.choice(chars) for _ in range(8))
    gif_name = f"{len(images):03}X{delay:03}{random_string}.gif"

    # Creating gif
    images_in_gif = [Image.open(image) for image in images]
    images_in_gif[0].save(os.path.join("gifs", gif_name), save_all=True, append_images=images_in_gif[1:], duration=float(delay), loop=0)

    print(f"Combined images into GIF: {gif_name}")

# Crating the "gifs" directory if it does not exist
if not os.path.exists("gifs"):
    os.makedirs("gifs")

combine_images("output")